// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: example_service/v1/example_service.proto

package example_servicev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/bufbuild/buf-tour/gen/example_service/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ExampleServiceName is the fully-qualified name of the ExampleService service.
	ExampleServiceName = "example_service.v1.ExampleService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ExampleServiceTypeProcedure is the fully-qualified name of the ExampleService's Type RPC.
	ExampleServiceTypeProcedure = "/example_service.v1.ExampleService/Type"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	exampleServiceServiceDescriptor    = v1.File_example_service_v1_example_service_proto.Services().ByName("ExampleService")
	exampleServiceTypeMethodDescriptor = exampleServiceServiceDescriptor.Methods().ByName("Type")
)

// ExampleServiceClient is a client for the example_service.v1.ExampleService service.
type ExampleServiceClient interface {
	Type(context.Context, *connect.Request[v1.TypeRequest]) (*connect.Response[v1.TypeResponse], error)
}

// NewExampleServiceClient constructs a client for the example_service.v1.ExampleService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExampleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ExampleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &exampleServiceClient{
		_type: connect.NewClient[v1.TypeRequest, v1.TypeResponse](
			httpClient,
			baseURL+ExampleServiceTypeProcedure,
			connect.WithSchema(exampleServiceTypeMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// exampleServiceClient implements ExampleServiceClient.
type exampleServiceClient struct {
	_type *connect.Client[v1.TypeRequest, v1.TypeResponse]
}

// Type calls example_service.v1.ExampleService.Type.
func (c *exampleServiceClient) Type(ctx context.Context, req *connect.Request[v1.TypeRequest]) (*connect.Response[v1.TypeResponse], error) {
	return c._type.CallUnary(ctx, req)
}

// ExampleServiceHandler is an implementation of the example_service.v1.ExampleService service.
type ExampleServiceHandler interface {
	Type(context.Context, *connect.Request[v1.TypeRequest]) (*connect.Response[v1.TypeResponse], error)
}

// NewExampleServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExampleServiceHandler(svc ExampleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	exampleServiceTypeHandler := connect.NewUnaryHandler(
		ExampleServiceTypeProcedure,
		svc.Type,
		connect.WithSchema(exampleServiceTypeMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/example_service.v1.ExampleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ExampleServiceTypeProcedure:
			exampleServiceTypeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedExampleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExampleServiceHandler struct{}

func (UnimplementedExampleServiceHandler) Type(context.Context, *connect.Request[v1.TypeRequest]) (*connect.Response[v1.TypeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("example_service.v1.ExampleService.Type is not implemented"))
}
