// @generated by protoc-gen-es v1.10.0
// @generated from file example_service/v1/example_service.proto (package example_service.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { DateTime } from "../../google/type/datetime_pb.js";

/**
 * @generated from message example_service.v1.TypeRequest
 */
export declare class TypeRequest extends Message<TypeRequest> {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  constructor(data?: PartialMessage<TypeRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "example_service.v1.TypeRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TypeRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TypeRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TypeRequest;

  static equals(a: TypeRequest | PlainMessage<TypeRequest> | undefined, b: TypeRequest | PlainMessage<TypeRequest> | undefined): boolean;
}

/**
 * @generated from message example_service.v1.TypeResponse
 */
export declare class TypeResponse extends Message<TypeResponse> {
  /**
   * @generated from field: example_service.v1.Type type = 1;
   */
  type?: Type;

  constructor(data?: PartialMessage<TypeResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "example_service.v1.TypeResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TypeResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TypeResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TypeResponse;

  static equals(a: TypeResponse | PlainMessage<TypeResponse> | undefined, b: TypeResponse | PlainMessage<TypeResponse> | undefined): boolean;
}

/**
 * @generated from message example_service.v1.Type
 */
export declare class Type extends Message<Type> {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: google.type.DateTime created_at = 3;
   */
  createdAt?: DateTime;

  constructor(data?: PartialMessage<Type>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "example_service.v1.Type";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Type;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Type;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Type;

  static equals(a: Type | PlainMessage<Type> | undefined, b: Type | PlainMessage<Type> | undefined): boolean;
}

