// @generated by protoc-gen-es v1.10.0
// @generated from file example_service/v1/example_service.proto (package example_service.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { DateTime } from "../../google/type/datetime_pb.js";

/**
 * @generated from message example_service.v1.TypeRequest
 */
export const TypeRequest = /*@__PURE__*/ proto3.makeMessageType(
  "example_service.v1.TypeRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ],
);

/**
 * @generated from message example_service.v1.TypeResponse
 */
export const TypeResponse = /*@__PURE__*/ proto3.makeMessageType(
  "example_service.v1.TypeResponse",
  () => [
    { no: 1, name: "type", kind: "message", T: Type },
  ],
);

/**
 * @generated from message example_service.v1.Type
 */
export const Type = /*@__PURE__*/ proto3.makeMessageType(
  "example_service.v1.Type",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "created_at", kind: "message", T: DateTime },
  ],
);

